import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/auth/AuthProvider";
import Header from "@/components/header/Header";
import AuthGuard from "@/components/auth/AuthGuard";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
       

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <Suspense fallback={<div>Loading...</div>}>
        
        <AuthProvider>
        <Header />
        <AuthGuard>{children}</AuthGuard>

        

        </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
